# MAIN SETTINGS
iterations: 110
learning_rate: 0.1

mesh_size: 11
camera_distance: 5
mesh_normalize: True
texture_size: 100 # 0 for none
sigmainv: 7000
factor: 1
number_of_pieces: 2
number_of_terms: 3

# LOSS FUNCTION
loss_use_supervised: True
loss_use_model: False
loss_iou_weight: 1.0
loss_total_variation: 1.0
loss_laplacian_weight: 1000.0
# experimental
loss_jointm_iou_weight: 0
loss_rgb_weight: 0
loss_mask_weight: 0

erode_renderer_mask: 0
rotation_divide: 2.0

shapes:
  - sphere
  - sphere_voronoi
  - torus_voronoi
predict_vertices_list: 
  - True
  - False

verbose: True
